spring:
  datasource:
#    url: jdbc:mysql://120.76.136.118:3306/wanba?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/wanba?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: langu002
    jmx-enabled: true
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    test-on-return: false
    validation-interval: 30000
    time-between-eviction-runs-millis: 30000
    max-active: 100
    initial-size: 10
    max-wait: 10000
    remove-abandoned-timeout: 60
    min-evictable-idle-time-millis: 30000
    min-idle: 10
    log-abandoned: true
    remove-abandoned: true
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 120.76.136.118
    password: langu1234
    port: 6379
    pool:
      max-wait: 5000
      max-active: 500
      max-idle: 8
    timeout: 1000

  jackson:
    serialization-inclusion: non_null
task:
  pool:
    size: 6
  queue:
    capacity: 20

mybatis:
  typeAliasesPackage: com.langu.wanba.core.data.domain
  configLocation: classpath:mybatis/mybatis.xml
  mapperLocations: classpath:mybatis/sql/*.xml

emchat:
  host: https://a1.easemob.com
  password: 123456
  appkey: pingke#yungo-test
  clientId: YXA6Rc6j0Hz5EeanSeU_LEl1aQ
  secret: YXA6NuO-NjzTOgXe444wxLbgAtZG6Vg

pay:
  host: http://120.76.136.118:8099
  aliUrl: /api/pay/notify/alipay
  aliVirtualUrl: /api/pay/virtual/notify/alipay
  wepayUrl: /api/pay/notify/wepay
  applePayVipUrl: https://buy.itunes.apple.com/verifyReceipt
  applePayVipUrlSandbox: https://sandbox.itunes.apple.com/verifyReceipt
  debug: true

server:
  port: 8099

switch:
  debug: true